global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node'
    dns_sd_configs:
      - names: ['tasks.drove-mon-node-exporter']
        type: A
        port: 9100
  - job_name: 'cadvisor'
    dns_sd_configs:
      - names: ['tasks.drove-mon-cadvisor']
        type: A
        port: 8080
  - job_name: 'prometheus'
    dns_sd_configs:
      - names: ['tasks.drove-mon-prometheus']
        type: A
        port: 9090
